---
- hosts: node
  tasks:
  - name: Ansible create new file with permissions example.
    file:
      path: "/home/ec2-user/madhu/todays.txt"
      state: touch
      mode: 0777
      owner: ec2-user

