---
# tasks file for tomcat
- name: Install basic software
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - java-1.7.0-openjdk
    - tomcat7
    - tomcat-webapps
    - tomcat-docs-webapp
    - tomcat-admin-webapps
- name: copy arti facts to remote server
  copy:
     src: /home/ec2-user/sample.war
     dest: /home/ec2-user/madhu/sample.war
     owner: ec2-user
     group: ec2-user
     remote_src: yes
- name: copy arti facts to tomcat server
  copy:
     src: /home/ec2-user/madhu/sample.war
     dest: /usr/share/tomcat/webapps/
     remote_src: yes
- name: restart httpd
  service:
     name: tomcat7
     state: restarted
